# Generated by Django 5.2.7 on 2025-10-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfFailure',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id_office', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование подразделения')),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('parent_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_offices', to='back.office', verbose_name='ID_офиса_родителя')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.office', verbose_name='FK Офис')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='back.user', verbose_name='FK руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('urgency', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('office_location', models.CharField(max_length=255)),
                ('employee_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('due_time', models.DateTimeField(blank=True, null=True)),
                ('comments', models.ManyToManyField(blank=True, to='back.comment')),
                ('office_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.office', verbose_name='FK Адрес офиса')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.status', verbose_name='Статус')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.table', verbose_name='FK таблица затрат')),
                ('failure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.typeoffailure', verbose_name='Тип поломки')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='back.user', verbose_name='FK Исполнитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='back.user', verbose_name='FK Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices_supervised', to='back.user', verbose_name='FirstKey Руководитель'),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id_load', models.AutoField(primary_key=True, serialize=False)),
                ('current_tasks_count', models.IntegerField()),
                ('current_tasks', models.TextField()),
                ('urgency', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='back.user', verbose_name='FK Сотрудник АХО')),
            ],
        ),
    ]
