# Generated by Django 4.2.7 on 2025-11-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_user_email_user_password_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='desk_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер стола'),
        ),
    ]
