# Generated by Django 4.2.7 on 2025-11-23 05:32

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_user_birth_date_user_desk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=back.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
