# Generated by Django 5.2.7 on 2025-12-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id_attachment', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_attachments', to='back.request', verbose_name='FK Заявка')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
